- .expo/settings.json
- AppCode/app/screens/Lesson1DetailsScreen.js
- AppCode/package-lock.json
- AppCode/package.json
Added a sample video to the lesson details page. I added the video as an asset for now because I was not able to access it on the server. We can change that once resolve the issue with the server account.
> add sample video

- AppCode/.vscode/launch.json
- AppCode/App.js
- AppCode/app/components/Card.js
- AppCode/app/components/ListItem.js
- AppCode/app/components/ListItemSeparator.js
- AppCode/app/components/Screen.js
- AppCode/app/config/colors.js
- AppCode/app/navigation/AppNavigator.js
- AppCode/app/navigation/LessonsNavigator.js
- AppCode/app/navigation/navigationTheme.js
- AppCode/app/navigation/routes.js
- AppCode/app/screens/AccountScreen.js
- AppCode/app/screens/LessonDetailsScreen.js
- AppCode/app/screens/LessonsScreen.js
- AppCode/package-lock.json
- AppCode/package.json
Add tab navigation at the bottom of the app, for LessonsScreen and AccountScreen.
Add stack navigation between LessonsScreen and LessonDetailsScreen.
Pass video as parameter to LessonDetailsScreen.
> Add Navigation 

- AppCode/App.js
- AppCode/app/components/AppText.js
- AppCode/app/components/AppTextInput.js
- AppCode/app/components/ListItem.js
- AppCode/app/components/ListItemSeparator.js
- AppCode/app/components/Screen.js
- AppCode/app/components/forms/AppForm.js
- AppCode/app/components/forms/AppFormField.js
- AppCode/app/components/forms/ErrorMessage.js
- AppCode/app/components/forms/SubmitButton.js
- AppCode/app/components/forms/index.js
- AppCode/app/config/colors.js
- AppCode/app/config/styles.js
- AppCode/app/navigation/AppNavigator.js
- AppCode/app/navigation/LessonsNavigator.js
- AppCode/app/screens/LessonDetailsScreen.js
- AppCode/app/screens/LoginScreen.js
- AppCode/app/screens/RegisterScreen.js
- AppCode/app/screens/ToolboxScreen.js
- AppCode/app/screens/WelcomeScreen.js
- AppCode/package-lock.json
- AppCode/package.json
1. Add LoginScreen and RegisterScreen, navigation hasn't been added yet.
2. Add Toolbox tab and ToolboxScreen.
3. Remove image on LessonDetailsScreen.
> Add LoginScreen and ToolboxScreen

- AppCode/app/components/ActivityListItem.js
- AppCode/app/components/Status.js
- AppCode/app/navigation/LessonsNavigator.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/LessonDetailsScreen.js
Adding following changes:
1) Add status control on activity (color of the icons need to be tweaked)
2) Make activity video to play in full screen mode
Tried to limit the code change to minimum. There are still ToDos such as add Replay button.
> 1) Add status control on activity; 2) make activity video to play in full screen mode

- AppCode/App.js
- AppCode/app/auth/storage.js
- AppCode/app/auth/useAuth.js
- AppCode/app/screens/AccountScreen.js
- AppCode/app/screens/LoginScreen.js
- AppCode/package.json
When restarting/reloading the app, it will remember your login information and directly goes to LessonsScreen.
> Persist the Authentication State Across Restarts.

- AppCode/app/components/ActivityListItem.js
- AppCode/app/components/Status.js
- AppCode/app/screens/LessonDetailsScreen.js
- AppCode/package-lock.json
1. Update Lesson & Activity layouts
2. Add duration information
3. Display Activity Id & Name instead
4. Refactor the styles code
> Update Lesson Activity visual based on the Figma spec

- AppCode/app/components/ActivityListItem.js
- AppCode/app/screens/LessonDetailsScreen.js
1. Update the layout so everything will show properly on both Android & iPhone
2. Round up the video length to minutes
> Adjust Lesson and Activity layout for Android

- AppCode/app/navigation/AppNavigator.js
- AppCode/app/navigation/SettingsNavigator.js
- AppCode/app/navigation/routes.js
- AppCode/app/screens/AccountDetailsScreen.js
- AppCode/app/screens/LanguageScreen.js
- AppCode/app/screens/NotificationsScreen.js
- AppCode/app/screens/PrivacyPolicyScreen.js
- AppCode/app/screens/SettingScreen.js
- AppCode/app/screens/TermsAndConditionsScreen.js
I added a screen for each of the tabs on the Settings page and added some sample text. We can fill these in with the actual text for the terms and conditions or the privacy policy.
> Add screens for each of the settings pages

- AppCode/app/api/auth.js
- AppCode/app/screens/PasswordResetScreen.js
- AppCode/app/screens/SettingScreen.js
Connect to password reset api. 
Fix bug in SettingScreen.
> Connect to password reset api. 

- AppCode/app/api/status.js
- AppCode/app/components/ActivityListItem.js
- AppCode/app/components/ActivityStatus.js
- AppCode/app/components/LessonListItem.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/HomeScreen.js
- AppCode/app/screens/LessonDetailsScreen.js
1) Connect to use Web API to retrieve the latest activity status;
2) Calculate percent completion of a lesson based on the activity progress under each lesson;
3) Code refactor (renaming)
https://user-images.githubusercontent.com/76028304/124234756-4cff1800-dac9-11eb-8e79-3227f24adefc.mp4
> Update lesson progress at Home Screen based on the real-time data

- AppCode/App.js
- AppCode/app/data/lesson/lessoncontext.js
- AppCode/app/data/lesson/lessondata.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/HomeScreen.js
- AppCode/app/screens/LessonDetailsScreen.js
1) Create a global lesson / status object - so it could be accessible from any pages;
2) Consolidate status related functions from three places to one - remove the duplicate codes;
3) Better names for functions - to make the purpose of function clear;
4) Additional error handling - check response from API call before accessing the file
> Code refactoring for Lesson and activities related function

- AppCode/app/screens/LessonDetailsScreen.js
Thanks Lin Sung for solving this issue!
Closes #82
> Fix lesson1 crash issue.

- AppCode/app/screens/LessonDetailsScreen.js
> Fix the issue so it could scroll to the last item at activity lists

- AppCode/app/components/AppTextInput.js
Fix issue #83 : hard to enter email and password.
> Fix issue #83: hard to enter email and password.

- AppCode/app/screens/SongListScreen.js
Fix issue #86 : Music won't stop when navigating to other screens on iOS.
> Fix music won't stop issue.

- AppCode/app/components/AppTextInput.js
- AppCode/app/screens/LoginScreen.js
- AppCode/app/screens/RegisterScreen.js
> Add toggle to view password.

- AppCode/app/api/lessons.js
- AppCode/app/components/ActivityListItem.js
- AppCode/app/components/forms/ErrorMessage.js
- AppCode/app/config/uistrings.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/HomeScreen.js
- AppCode/app/screens/LessonDetailsScreen.js
- AppCode/package-lock.json
This is part of fixes/mitigations to address #110. Refer to the issue itself for detail.
Specifically this change contains:
1. Add "pull to refresh" function to Home, Lesson, and Activity Screen;
2. Turn off Auto Play when video loads;
3. Additional logging;
4. As part of updating Activity Screen, adjust video control to fit in the scroll viewer so it won't overlap with Back button.
> Add ability to pull to reload the media contents

- AppCode/app/components/LoadingIndicator.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/HomeScreen.js
- AppCode/app/screens/LessonDetailsScreen.js
This is part of continuing fix for issue #110.
> Render only when the video uri becomes available, otherwise show loading indicator

- AppCode/app/screens/SongListScreen.js
Solving Issue #142 
Check whether the audio didJustFinish by method setOnPlaybackStatusUpdate(), which check audio play status every 0.5 second.
> Fix bug: Song cannot be resumed

- AppCode/app/api/user.js
- AppCode/app/config/colors.js
- AppCode/app/config/uistrings.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/SettingScreen.js
- AppCode/package-lock.json
1) Add "Delete User" button under Settings page that calls webserice API to remove user, status activity and reward data (issue #167) (screenshot - https://user-images.githubusercontent.com/76028304/183824547-dab0e0e0-aee8-4687-a035-eaee0ecaef72.png)
2) Fix incorrect counting of activity repeat counts
> Add a way for users to delete their account

- AppCode/app/screens/PrivacyPolicyScreen.js
> Update Privacy Policy in app

- AppCode/app/config/uistrings.js
- AppCode/app/navigation/AuthNavigator.js
- AppCode/app/navigation/routes.js
- AppCode/app/screens/LoginScreen.js
- AppCode/app/screens/NavigationScreen.js
- AppCode/app/screens/RegisterScreen.js
> Add NavigationScreen.

- AppCode/app/components/ActivityCompletion.js
- AppCode/app/components/ActivityListItem.js
- AppCode/app/components/ActivityVideoControl.js
- AppCode/app/components/LessonListItem.js
- AppCode/app/components/PracticeModeCamera.js
- AppCode/app/components/RecordIcon.js
- AppCode/app/components/ScoreNotification.js
- AppCode/app/components/StopIcon.js
- AppCode/app/screens/ActivityDetailsScreen.js
- AppCode/app/screens/HomeScreen.js
- AppCode/yarn.lock
1) Change PracticeMode icon to be "video"
2) Adjust the Activity Completion UI per activity video size
3) Not to promote Welcome screen
4) Separate PracticeMode code out to its own component
5) Tweak LessonListItem to handle long lesson name
> Tweak PracticeMode to be able to handle additional lesson contents

- AppCode/app/components/PracticeModeCamera.js
1. set permission on Android;
2. change camera ratio
> Fix Practice Mode camera issue on Android
